// **********************************************************************
// Parsed By TarsParser(1.1.0), Generated By tools(20180620)
// TarsParser Maintained By <WSRD> and tools Maintained By <superzheng>
// Generated from "QueryTracing.tars" by Client Mode
// **********************************************************************

"use strict";

var assert    = require("assert");
var TarsStream = require("@tars/stream");
var TarsError  = require("@tars/rpc").error;

var tars = tars || {};
module.exports.tars = tars;

tars.QueryControllerProxy = function () {
    this._name   = undefined;
    this._worker = undefined;
};

tars.QueryControllerProxy.prototype.setTimeout = function (iTimeout) {
    this._worker.timeout = iTimeout;
};

tars.QueryControllerProxy.prototype.getTimeout = function () {
    return this._worker.timeout;
};


tars.TracingAnalysisReq = function() {
    this.serviceName = "";
    this.start = 0;
    this.end = 0;
    this._classname = "tars.TracingAnalysisReq";
};
tars.TracingAnalysisReq._classname = "tars.TracingAnalysisReq";
tars.TracingAnalysisReq._write = function (os, tag, value) { os.writeStruct(tag, value); };
tars.TracingAnalysisReq._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
tars.TracingAnalysisReq._readFrom = function (is) {
    var tmp = new tars.TracingAnalysisReq();
    tmp.serviceName = is.readString(0, true, "");
    tmp.start = is.readInt64(1, true, 0);
    tmp.end = is.readInt64(2, true, 0);
    return tmp;
};
tars.TracingAnalysisReq.prototype._writeTo = function (os) {
    os.writeString(0, this.serviceName);
    os.writeInt64(1, this.start);
    os.writeInt64(2, this.end);
};
tars.TracingAnalysisReq.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
tars.TracingAnalysisReq.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
tars.TracingAnalysisReq.prototype.toObject = function() { 
    return {
        "serviceName" : this.serviceName,
        "start" : this.start,
        "end" : this.end
    };
};
tars.TracingAnalysisReq.prototype.readFromObject = function(json) { 
    json.hasOwnProperty("serviceName") && (this.serviceName = json.serviceName);
    json.hasOwnProperty("start") && (this.start = json.start);
    json.hasOwnProperty("end") && (this.end = json.end);
};
tars.TracingAnalysisReq.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
tars.TracingAnalysisReq.new = function () {
    return new tars.TracingAnalysisReq();
};
tars.TracingAnalysisReq.create = function (is) {
    return tars.TracingAnalysisReq._readFrom(is);
};

tars.DependencyLink = function() {
    this.parent = "";
    this.child = "";
    this._classname = "tars.DependencyLink";
};
tars.DependencyLink._classname = "tars.DependencyLink";
tars.DependencyLink._write = function (os, tag, value) { os.writeStruct(tag, value); };
tars.DependencyLink._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
tars.DependencyLink._readFrom = function (is) {
    var tmp = new tars.DependencyLink();
    tmp.parent = is.readString(0, true, "");
    tmp.child = is.readString(1, true, "");
    return tmp;
};
tars.DependencyLink.prototype._writeTo = function (os) {
    os.writeString(0, this.parent);
    os.writeString(1, this.child);
};
tars.DependencyLink.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
tars.DependencyLink.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
tars.DependencyLink.prototype.toObject = function() { 
    return {
        "parent" : this.parent,
        "child" : this.child
    };
};
tars.DependencyLink.prototype.readFromObject = function(json) { 
    json.hasOwnProperty("parent") && (this.parent = json.parent);
    json.hasOwnProperty("child") && (this.child = json.child);
};
tars.DependencyLink.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
tars.DependencyLink.new = function () {
    return new tars.DependencyLink();
};
tars.DependencyLink.create = function (is) {
    return tars.DependencyLink._readFrom(is);
};

tars.ToPoGraph = function() {
    this.links = new TarsStream.List(tars.DependencyLink);
    this._classname = "tars.ToPoGraph";
};
tars.ToPoGraph._classname = "tars.ToPoGraph";
tars.ToPoGraph._write = function (os, tag, value) { os.writeStruct(tag, value); };
tars.ToPoGraph._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
tars.ToPoGraph._readFrom = function (is) {
    var tmp = new tars.ToPoGraph();
    tmp.links = is.readList(0, true, TarsStream.List(tars.DependencyLink));
    return tmp;
};
tars.ToPoGraph.prototype._writeTo = function (os) {
    os.writeList(0, this.links);
};
tars.ToPoGraph.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
tars.ToPoGraph.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
tars.ToPoGraph.prototype.toObject = function() { 
    return {
        "links" : this.links.toObject()
    };
};
tars.ToPoGraph.prototype.readFromObject = function(json) { 
    json.hasOwnProperty("links") && (this.links.readFromObject(json.links));
};
tars.ToPoGraph.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
tars.ToPoGraph.new = function () {
    return new tars.ToPoGraph();
};
tars.ToPoGraph.create = function (is) {
    return tars.ToPoGraph._readFrom(is);
};

tars.ChainNodeItem = function() {
    this.serviceName = "";
    this.method = "";
    this.order = 0;
    this.layer = 0;
    this.QPS = 0;
    this.peakQPS = 0;
    this.callPercent = 0;
    this.avgCost = 0;
    this.failRate = 0;
    this._classname = "tars.ChainNodeItem";
};
tars.ChainNodeItem._classname = "tars.ChainNodeItem";
tars.ChainNodeItem._write = function (os, tag, value) { os.writeStruct(tag, value); };
tars.ChainNodeItem._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
tars.ChainNodeItem._readFrom = function (is) {
    var tmp = new tars.ChainNodeItem();
    tmp.serviceName = is.readString(0, true, "");
    tmp.method = is.readString(1, true, "");
    tmp.order = is.readInt32(2, true, 0);
    tmp.layer = is.readInt32(3, true, 0);
    tmp.QPS = is.readInt32(4, true, 0);
    tmp.peakQPS = is.readInt32(5, true, 0);
    tmp.callPercent = is.readFloat(6, true, 0);
    tmp.avgCost = is.readInt32(7, true, 0);
    tmp.failRate = is.readFloat(8, true, 0);
    return tmp;
};
tars.ChainNodeItem.prototype._writeTo = function (os) {
    os.writeString(0, this.serviceName);
    os.writeString(1, this.method);
    os.writeInt32(2, this.order);
    os.writeInt32(3, this.layer);
    os.writeInt32(4, this.QPS);
    os.writeInt32(5, this.peakQPS);
    os.writeFloat(6, this.callPercent);
    os.writeInt32(7, this.avgCost);
    os.writeFloat(8, this.failRate);
};
tars.ChainNodeItem.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
tars.ChainNodeItem.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
tars.ChainNodeItem.prototype.toObject = function() { 
    return {
        "serviceName" : this.serviceName,
        "method" : this.method,
        "order" : this.order,
        "layer" : this.layer,
        "QPS" : this.QPS,
        "peakQPS" : this.peakQPS,
        "callPercent" : this.callPercent,
        "avgCost" : this.avgCost,
        "failRate" : this.failRate
    };
};
tars.ChainNodeItem.prototype.readFromObject = function(json) { 
    json.hasOwnProperty("serviceName") && (this.serviceName = json.serviceName);
    json.hasOwnProperty("method") && (this.method = json.method);
    json.hasOwnProperty("order") && (this.order = json.order);
    json.hasOwnProperty("layer") && (this.layer = json.layer);
    json.hasOwnProperty("QPS") && (this.QPS = json.QPS);
    json.hasOwnProperty("peakQPS") && (this.peakQPS = json.peakQPS);
    json.hasOwnProperty("callPercent") && (this.callPercent = json.callPercent);
    json.hasOwnProperty("avgCost") && (this.avgCost = json.avgCost);
    json.hasOwnProperty("failRate") && (this.failRate = json.failRate);
};
tars.ChainNodeItem.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
tars.ChainNodeItem.new = function () {
    return new tars.ChainNodeItem();
};
tars.ChainNodeItem.create = function (is) {
    return tars.ChainNodeItem._readFrom(is);
};

tars.ChainShape = function() {
    this.shape = new TarsStream.List(tars.ChainNodeItem);
    this.rootSign = "";
    this._classname = "tars.ChainShape";
};
tars.ChainShape._classname = "tars.ChainShape";
tars.ChainShape._write = function (os, tag, value) { os.writeStruct(tag, value); };
tars.ChainShape._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
tars.ChainShape._readFrom = function (is) {
    var tmp = new tars.ChainShape();
    tmp.shape = is.readList(0, true, TarsStream.List(tars.ChainNodeItem));
    tmp.rootSign = is.readString(1, false, "");
    return tmp;
};
tars.ChainShape.prototype._writeTo = function (os) {
    os.writeList(0, this.shape);
    os.writeString(1, this.rootSign);
};
tars.ChainShape.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
tars.ChainShape.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
tars.ChainShape.prototype.toObject = function() { 
    return {
        "shape" : this.shape.toObject(),
        "rootSign" : this.rootSign
    };
};
tars.ChainShape.prototype.readFromObject = function(json) { 
    json.hasOwnProperty("shape") && (this.shape.readFromObject(json.shape));
    json.hasOwnProperty("rootSign") && (this.rootSign = json.rootSign);
};
tars.ChainShape.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
tars.ChainShape.new = function () {
    return new tars.ChainShape();
};
tars.ChainShape.create = function (is) {
    return tars.ChainShape._readFrom(is);
};

tars.ChainShapeCollection = function() {
    this.timestamp = "";
    this.chainShapes = new TarsStream.Map(TarsStream.String, tars.ChainShape);
    this._classname = "tars.ChainShapeCollection";
};
tars.ChainShapeCollection._classname = "tars.ChainShapeCollection";
tars.ChainShapeCollection._write = function (os, tag, value) { os.writeStruct(tag, value); };
tars.ChainShapeCollection._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
tars.ChainShapeCollection._readFrom = function (is) {
    var tmp = new tars.ChainShapeCollection();
    tmp.timestamp = is.readString(0, true, "");
    tmp.chainShapes = is.readMap(1, true, TarsStream.Map(TarsStream.String, tars.ChainShape));
    return tmp;
};
tars.ChainShapeCollection.prototype._writeTo = function (os) {
    os.writeString(0, this.timestamp);
    os.writeMap(1, this.chainShapes);
};
tars.ChainShapeCollection.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
tars.ChainShapeCollection.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
tars.ChainShapeCollection.prototype.toObject = function() { 
    return {
        "timestamp" : this.timestamp,
        "chainShapes" : this.chainShapes.toObject()
    };
};
tars.ChainShapeCollection.prototype.readFromObject = function(json) { 
    json.hasOwnProperty("timestamp") && (this.timestamp = json.timestamp);
    json.hasOwnProperty("chainShapes") && (this.chainShapes.readFromObject(json.chainShapes));
};
tars.ChainShapeCollection.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
tars.ChainShapeCollection.new = function () {
    return new tars.ChainShapeCollection();
};
tars.ChainShapeCollection.create = function (is) {
    return tars.ChainShapeCollection._readFrom(is);
};

tars.TracingAnalysisRes = function() {
    this.dependencyGraph = new tars.ToPoGraph;
    this.chainShapes = new tars.ChainShapeCollection;
    this._classname = "tars.TracingAnalysisRes";
};
tars.TracingAnalysisRes._classname = "tars.TracingAnalysisRes";
tars.TracingAnalysisRes._write = function (os, tag, value) { os.writeStruct(tag, value); };
tars.TracingAnalysisRes._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
tars.TracingAnalysisRes._readFrom = function (is) {
    var tmp = new tars.TracingAnalysisRes();
    tmp.dependencyGraph = is.readStruct(0, true, tars.ToPoGraph);
    tmp.chainShapes = is.readStruct(1, true, tars.ChainShapeCollection);
    return tmp;
};
tars.TracingAnalysisRes.prototype._writeTo = function (os) {
    os.writeStruct(0, this.dependencyGraph);
    os.writeStruct(1, this.chainShapes);
};
tars.TracingAnalysisRes.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
tars.TracingAnalysisRes.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
tars.TracingAnalysisRes.prototype.toObject = function() { 
    return {
        "dependencyGraph" : this.dependencyGraph.toObject(),
        "chainShapes" : this.chainShapes.toObject()
    };
};
tars.TracingAnalysisRes.prototype.readFromObject = function(json) { 
    json.hasOwnProperty("dependencyGraph") && (this.dependencyGraph.readFromObject(json.dependencyGraph));
    json.hasOwnProperty("chainShapes") && (this.chainShapes.readFromObject(json.chainShapes));
};
tars.TracingAnalysisRes.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
tars.TracingAnalysisRes.new = function () {
    return new tars.TracingAnalysisRes();
};
tars.TracingAnalysisRes.create = function (is) {
    return tars.TracingAnalysisRes._readFrom(is);
};


var __tars_QueryController$getQueryChainResult$EN = function (request) {
    var os = new TarsStream.TarsOutputStream();
    os.writeStruct(1, request);
    return os.getBinBuffer();
};

var __tars_QueryController$getQueryChainResult$DE = function (data) {
    try {
        var is = new TarsStream.TarsInputStream(data.response.sBuffer);
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : is.readStruct(0, true, tars.TracingAnalysisRes)
            }
        };
    } catch (e) {
        throw {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "error" : {
                    "code" : TarsError.CLIENT.DECODE_ERROR,
                    "message" : e.message
                }
            }
        };
    }
};

var __tars_QueryController$getQueryChainResult$ER = function (data) {
    throw {
        "request" : data.request,
        "response" : {
            "costtime" : data.request.costtime,
            "error" : data.error
        }
    }
};

tars.QueryControllerProxy.prototype.getQueryChainResult = function (request) {
    return this._worker.tars_invoke("getQueryChainResult", __tars_QueryController$getQueryChainResult$EN(request), arguments[arguments.length - 1]).then(__tars_QueryController$getQueryChainResult$DE, __tars_QueryController$getQueryChainResult$ER);
};



